../deps/async_fifo/src/vlog/async_bidir_fifo.v
../deps/async_fifo/src/vlog/async_bidir_ramif_fifo.v
../deps/async_fifo/src/vlog/async_fifo.v
../deps/async_fifo/src/vlog/fifo_2mem.v
../deps/async_fifo/src/vlog/fifomem_dp.v
../deps/async_fifo/src/vlog/rptr_empty.v
../deps/async_fifo/src/vlog/sync_ptr.v
../deps/async_fifo/src/vlog/sync_r2w.v
../deps/async_fifo/src/vlog/sync_w2r.v
../deps/async_fifo/src/vlog/wptr_full.v
../src/accounter.sv
../src/bram.sv
../src/bram_bank.sv
../src/mem_map_accounter.sv
../src/write_collision.sv
../src/read_collision.sv
../src/read_switch.sv
../src/axi4l_read.sv
../src/axi4l_write.sv
../src/top_2w_2r_core.sv
../src/top_2w_2r_axi4lite.sv
+define+VERBOSE
